/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern void initialise_monitor_handles(void);

int main(void)
{
	//initialise_monitor_handles();
    /* Loop forever */
	//printf("hello\n\r");

	//Enable all config exceptions like usage fault, mem manage, bus fault
	uint32_t* pSHCSR = (uint32_t *)0xE000ED24;

	//enable MEM_MANAGE, BUS_FAULT, USAGE_FAULT at once
	*pSHCSR |= (0x1 << 16);		//MEM_FAULT
	*pSHCSR |= (0x1 << 17);		//BUS_FAULT
	*pSHCSR |= (0x1 << 18);		//USAGE_FAULT

	//implement fault handlers

	//force the pro to execute undefined instructions
	uint32_t* pSRAM	=	(uint32_t *)(0x20001000);
	//write illegal code in SRAM code
	*pSRAM 			= 	0xFFFFFFFF;

	//send the processor to that area where illegal code is written
	void (*illegal_code)(void);
	illegal_code = (void *)(0x20001001);
	//make the pro execute the illegal code
	illegal_code();

	//analyze the fault

	for(;;);
}

void MemManage_Handler(void){
	while(1){}
}

void BusFault_Handler(void){
	while(1){}
}

void UsageFault_Handler(void){
	while(1){}
}
