/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern void initialise_monitor_handles(void);
int add(int, int, int, int);
void generate_exception(void);

int add(int a, int b, int c, int d){
	int val = 0;

	val = a+b+c+d;

	return val;
}

__attribute((naked)) void sp2psp(void){

	//assembler macros
	__asm volatile(".equ SRAM_START, 0x20000000");
	__asm volatile(".equ SRAM_SIZE, (128*1024)");
	__asm volatile(".equ SRAM_END, (SRAM_START + SRAM_SIZE)");
	__asm volatile(".equ MSP_START, (SRAM_END)");
	__asm volatile(".equ MSP_END, (SRAM_END - 512)");
	__asm volatile(".equ PSP_START, (MSP_END)");
	__asm volatile(".equ PSP_END, (PSP_START - 512)");

	//instructions to make SP point to PSP
	__asm volatile("LDR R0,=SRAM_START");
	__asm volatile("MSR PSP,R0");
	__asm volatile("MOV R0,#0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");
}


void generate_exception(void){
	__asm volatile("SVC #0x02");
}


int main(void)
{
	initialise_monitor_handles();
	sp2psp();

	int ret;
    /* Loop forever */
	printf("hello\n\r");

	ret = add(1,2,3,4);

	printf("The result is %d", ret);

	for(;;);
}
